from PyQt5 import QtCore, QtGui, QtWidgets
from Eight_puzzle_algo import *

class Ui_MainWindow(object):

    ListButton = []
    def __init__(self, problem, solving):
        self.problem = problem
        self.solution = tuple(solving.solution)
        self.state  = problem.initial
        self.action = list(solving.solution)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("background-color: #EDEFEC;")
        MainWindow.resize(400,480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(30, 60, 111, 111))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)

        self.btn0.setFont(font)
        self.btn0.setObjectName("btn0")
        self.btn0.setStyleSheet("border : 1px solid white; background-color : #07BF2F; color: yellow; border-radius : 10px")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("newgame_btn")
        self.pushButton_10.setStyleSheet("background-color: #36E303; color: black;")
        self.btn0_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0_2.setGeometry(QtCore.QRect(140, 60, 111, 111))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn0_2.setFont(font)
        self.btn0_2.setObjectName("btn0_2")
        self.btn0_2.setStyleSheet("border : 1px solid white; background-color : #07BF2F; color: yellow; border-radius : 10px")
        self.btn0_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0_3.setGeometry(QtCore.QRect(250, 60, 111, 111))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn0_3.setFont(font)
        self.btn0_3.setObjectName("btn0_3")
        self.btn0_3.setStyleSheet("border : 1px solid white; background-color : #07BF2F; color: yellow; border-radius : 10px")
        self.btn0_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0_4.setGeometry(QtCore.QRect(30, 170, 111, 111))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn0_4.setFont(font)
        self.btn0_4.setObjectName("btn0_4")
        self.btn0_4.setStyleSheet("border : 1px solid white; background-color : #07BF2F; color: yellow; border-radius : 10px")
        self.btn0_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0_5.setGeometry(QtCore.QRect(140, 170, 111, 111))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn0_5.setFont(font)
        self.btn0_5.setObjectName("btn0_5")
        self.btn0_5.setStyleSheet("border : 1px solid white; background-color : #07BF2F; color: yellow; border-radius : 10px")
        self.btn0_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0_6.setGeometry(QtCore.QRect(250, 170, 111, 111))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn0_6.setFont(font)
        self.btn0_6.setObjectName("btn0_6")
        self.btn0_6.setStyleSheet("border : 1px solid white; background-color : #07BF2F; color: yellow; border-radius : 10px")
        self.btn0_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0_7.setGeometry(QtCore.QRect(30, 280, 111, 111))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn0_7.setFont(font)
        self.btn0_7.setObjectName("btn0_7")
        self.btn0_7.setStyleSheet("border : 1px solid white; background-color : #07BF2F; color: yellow; border-radius : 10px")
        self.btn0_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0_8.setGeometry(QtCore.QRect(140, 280, 111, 111))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn0_8.setFont(font)
        self.btn0_8.setObjectName("btn0_8")
        self.btn0_8.setStyleSheet("border : 1px solid white; background-color : #07BF2F; color: yellow; border-radius : 10px")
        self.btn0_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0_9.setGeometry(QtCore.QRect(250, 280, 111, 111))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn0_9.setFont(font)
        self.btn0_9.setText("")
        self.btn0_9.setObjectName("btn0_9")
        self.btn0_9.setStyleSheet("border : 1px solid white; background-color : #07BF2F; color: yellow; border-radius : 10px")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 410, 81, 31))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("Reset_btn")
        self.pushButton_11.setStyleSheet("background-color: #36E303; color: black;")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(210, 410, 81, 31))
        font = QtGui.QFont()
        font.setFamily("ScoutCond Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("solve_btn")
        self.pushButton_12.setStyleSheet("background-color: #36E303; color: black;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 708, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.ListButton.append(self.btn0)
        self.ListButton.append(self.btn0_2)
        self.ListButton.append(self.btn0_3)
        self.ListButton.append(self.btn0_4)
        self.ListButton.append(self.btn0_5)
        self.ListButton.append(self.btn0_6)
        self.ListButton.append(self.btn0_7)
        self.ListButton.append(self.btn0_8)
        self.ListButton.append(self.btn0_9)

        self.pushButton_11.clicked.connect(self.Reset)
        self.pushButton_12.clicked.connect(self.Solve)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "8-puzzle Game "))
        self.btn0.setText(_translate("MainWindow", "1"))
        self.pushButton_10.setText(_translate("MainWindow", "New Game"))
        self.btn0_2.setText(_translate("MainWindow", "2"))
        self.btn0_3.setText(_translate("MainWindow", "3"))
        self.btn0_4.setText(_translate("MainWindow", "4"))
        self.btn0_5.setText(_translate("MainWindow", "5"))
        self.btn0_6.setText(_translate("MainWindow", "6"))
        self.btn0_7.setText(_translate("MainWindow", "7"))
        self.btn0_8.setText(_translate("MainWindow", "8"))
        self.pushButton_11.setText(_translate("MainWindow", "RESET"))
        self.pushButton_12.setText(_translate("MainWindow", "SOLVE"))

    def Reset(self):
        self.state = self.problem.initial
        self.action = list(self.solution)
        print(self.solution)
        for i in range(0,9):
            if (self.problem.initial[i]!=0):
                self.ListButton[i].setText(self.problem.initial[i].__str__())
            else:
                self.ListButton[i].setText("")
        if (self.action):
            self.state = self.problem.Result(self.state,self.action[0])
            self.action.remove(self.action[0])

    def Solve(self):
        for i in range(0,9):
            if (self.state[i]!=0):
                self.ListButton[i].setText(self.state[i].__str__())
            else:
                self.ListButton[i].setText("")
        if (self.action):
            self.state = self.problem.Result(self.state,self.action[0])
            self.action.remove(self.action[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.Reset()
    MainWindow.show()
    sys.exit(app.exec_())