from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(60, 30, 101, 91))

        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn0.setFont(font)
        self.btn0.setObjectName("btn0")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(160, 30, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(260, 30, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(60, 120, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(160, 120, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(260, 120, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn5.setFont(font)
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(60, 210, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn6.setFont(font)
        self.btn6.setObjectName("btn6")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(160, 210, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(260, 210, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn8.setFont(font)
        self.btn8.setText("")
        self.btn8.setObjectName("btn8")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(130, 330, 161, 51))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 400, 161, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 708, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "8-puzzle Game"))
        self.btn0.setText(_translate("MainWindow", "1"))
        self.btn1.setText(_translate("MainWindow", "2"))
        self.btn2.setText(_translate("MainWindow", "3"))
        self.btn3.setText(_translate("MainWindow", "4"))
        self.btn4.setText(_translate("MainWindow", "5"))
        self.btn5.setText(_translate("MainWindow", "6"))
        self.btn6.setText(_translate("MainWindow", "7"))
        self.btn7.setText(_translate("MainWindow", "8"))
        self.pushButton_10.setText(_translate("MainWindow", "RESET"))
        self.pushButton_10.setStyleSheet("background-color : #A2ACA5")
        self.pushButton_11.setText(_translate("MainWindow", "SOLVE"))
        self.pushButton_11.setStyleSheet("background-color : #A2ACA5")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
